server.port=8082

spring.application.name=inventory-service

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/StockFlow}


# JWT
jwt.secret=${JWT_SECRET:ThisIsAVeryStrongSecretKeyForStockWiseJWTAuthentication2024!@#}

# SpringDoc
springdoc.api-docs.path=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.stockwise.inventory=DEBUG
