server.port=8084

spring.application.name=purchase-order-service

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/StockFlow}

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Feign Client Downstream URLs
inventory-service.url=${INVENTORY_SERVICE_URL:http://localhost:8082}

# JWT
jwt.secret=${JWT_SECRET:ThisIsAVeryStrongSecretKeyForStockWiseJWTAuthentication2024!@#}

# SpringDoc
springdoc.api-docs.path=/v3/api-docs

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.stockwise.purchaseorder=DEBUG
